name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create pages under www
        run: |
          mkdir -p www
          find mcp -type f | node index.mjs www
          echo ${{ github.sha }} > www/index.html
          find www -type f
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'www'
      - uses: actions/deploy-pages@v5
        id: deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
